name: Continuous Integration

on:
  push:
    branches:
    - staging
    - trying
  pull_request:

jobs:
  build:
    name: Build and Test Job
    timeout-minutes: 360
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nixpkgs: [ lockfile, nixos-19.09, nixos-unstable ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v13

    - name: nix-build (for ${{ matrix.nixpkgs }})
      env:
        NIXPKGS_CHANNEL: ${{ matrix.nixpkgs }}
      run: nix-build --no-link release.nix --arg nixpkgs "channel:$NIXPKGS_CHANNEL"
